services:
  web:
    image: ghcr.io/jcm102/budget:latest
    container_name: tasktrack-budget
    ports:
      - "9002:9002"
    environment:
      - NODE_ENV=production
      - PORT=9002
    env_file:
      - .env
    restart: unless-stopped
